### PR TITLE
Db 3952 migrate documentation

### PR DESCRIPTION
**Pull request by MiguelAHM**

### CODE REVIEW

**Comment by eshryane** [comment]
I suggest adding a brief introduction and build instructions to the root README.md

**Comment by eshryane** [comment]
The term *RIPE Database* is not capitalised properly in the titles (it appears as *Ripe Database*). We can fix that separately (I think it needs a code change?)

**Comment by MiguelAHM** [comment]
> The term _RIPE Database_ is not capitalised properly in the titles (it appears as _Ripe Database_). We can fix that separately (I think it needs a code change?)

It is not so complicated, I feel conformable doing in this jira ticket

**Comment by eshryane** [comment]
Section numbers are missing. This can be useful to refer to a section of the document, but makes the document more rigid (it's harder to make changes). We can discuss this separately.

**Comment by eshryane** [comment]
The section title "How to Query the RIPE Database" appears with a dash on the left-hand menu ("How to Query-the").

Also "Access to Personal Data" appears as "Access to Personal-Data"

**Comment by eshryane** [comment]
Some sections have a table of contents as the first page (e.g. "RIPE Database Structure") and some do not (e.g. "RPSL Object Types"). This is consistent with the current documentation so we don't have to change it for now, but we need to choose one format or the other.

**Comment by eshryane** [comment]
There's an emoji in "Creating Set Objects" (the text `:(` is converted automatically). Can you escape the colon?

**Comment by eshryane** [comment]
In "The structure of a query", the sentence "The query flags may be before or after the query argument." is inside a code block but needs to be outside (it's plain text).

**Comment by MiguelAHM** [comment]
> There's an emoji in "Creating Set Objects" (the text `:)` is converted automatically). Can you escape the colon?

yeah, I tried to escape the colon doing (\:) but same issue

**Comment by MiguelAHM** [comment]
> The term _RIPE Database_ is not capitalised properly in the titles (it appears as _Ripe Database_). We can fix that separately (I think it needs a code change?)

Done

**Comment by MiguelAHM** [comment]
> The section title "How to Query the RIPE Database" appears with a dash on the left-hand menu ("How to Query-the").
> 
> Also "Access to Personal Data" appears as "Access to Personal-Data"

Done

> In "The structure of a query", the sentence "The query flags may be before or after the query argument." is inside a code block but needs to be outside (it's plain text).
> 
> Also "for example, --no-filtering dw-ripe" should be inside the code block.

**Review by eshryane — APPROVED** [review]

**Pull request merged**
